<?php

return [
    'AED' => ['name' => 'UAE Dirham', 'symbol' => 'AED', 'flag' => '🇦🇪'],
    'ARS' => ['name' => 'Argentine Peso', 'symbol' => 'ARS', 'flag' => '🇦🇷'],
    'AUD' => ['name' => 'Australian Dollar', 'symbol' => 'A$', 'flag' => '🇦🇺'],
    'BDT' => ['name' => 'Bangladeshi Taka', 'symbol' => '৳', 'flag' => '🇧🇩'],
    'BHD' => ['name' => 'Bahraini Dinar', 'symbol' => 'BHD', 'flag' => '🇧🇭'],
    'BND' => ['name' => 'Brunei Dollar', 'symbol' => 'BND', 'flag' => '🇧🇳'],
    'BRL' => ['name' => 'Brazilian Real', 'symbol' => 'R$', 'flag' => '🇧🇷'],
    'CAD' => ['name' => 'Canadian Dollar', 'symbol' => 'C$', 'flag' => '🇨🇦'],
    'CHF' => ['name' => 'Swiss Franc', 'symbol' => 'CHF', 'flag' => '🇨🇭'],
    'CLP' => ['name' => 'Chilean Peso', 'symbol' => 'CLP', 'flag' => '🇨🇱'],
    'CNY' => ['name' => 'Chinese Yuan', 'symbol' => '¥', 'flag' => '🇨🇳'],
    'COP' => ['name' => 'Colombian Peso', 'symbol' => 'COP', 'flag' => '🇨🇴'],
    'CZK' => ['name' => 'Czech Koruna', 'symbol' => 'Kc', 'flag' => '🇨🇿'],
    'DKK' => ['name' => 'Danish Krone', 'symbol' => 'kr', 'flag' => '🇩🇰'],
    'DZD' => ['name' => 'Algerian Dinar', 'symbol' => 'DZD', 'flag' => '🇩🇿'],
    'EGP' => ['name' => 'Egyptian Pound', 'symbol' => 'E£', 'flag' => '🇪🇬'],
    'ETB' => ['name' => 'Ethiopian Birr', 'symbol' => 'ETB', 'flag' => '🇪🇹'],
    'EUR' => ['name' => 'Euro', 'symbol' => '€', 'flag' => '🇪🇺'],
    'GBP' => ['name' => 'British Pound', 'symbol' => '£', 'flag' => '🇬🇧'],
    'GHS' => ['name' => 'Ghanaian Cedi', 'symbol' => 'GHS', 'flag' => '🇬🇭'],
    'HKD' => ['name' => 'Hong Kong Dollar', 'symbol' => 'HK$', 'flag' => '🇭🇰'],
    'HUF' => ['name' => 'Hungarian Forint', 'symbol' => 'Ft', 'flag' => '🇭🇺'],
    'IDR' => ['name' => 'Indonesian Rupiah', 'symbol' => 'Rp', 'flag' => '🇮🇩'],
    'ILS' => ['name' => 'Israeli New Shekel', 'symbol' => 'ILS', 'flag' => '🇮🇱'],
    'INR' => ['name' => 'Indian Rupee', 'symbol' => '₹', 'flag' => '🇮🇳'],
    'IQD' => ['name' => 'Iraqi Dinar', 'symbol' => 'IQD', 'flag' => '🇮🇶'],
    'IRR' => ['name' => 'Iranian Rial', 'symbol' => 'IRR', 'flag' => '🇮🇷'],
    'ISK' => ['name' => 'Icelandic Krona', 'symbol' => 'kr', 'flag' => '🇮🇸'],
    'JMD' => ['name' => 'Jamaican Dollar', 'symbol' => 'J$', 'flag' => '🇯🇲'],
    'JOD' => ['name' => 'Jordanian Dinar', 'symbol' => 'JOD', 'flag' => '🇯🇴'],
    'JPY' => ['name' => 'Japanese Yen', 'symbol' => '¥', 'flag' => '🇯🇵'],
    'KES' => ['name' => 'Kenyan Shilling', 'symbol' => 'KES', 'flag' => '🇰🇪'],
    'KRW' => ['name' => 'South Korean Won', 'symbol' => '₩', 'flag' => '🇰🇷'],
    'KWD' => ['name' => 'Kuwaiti Dinar', 'symbol' => 'KWD', 'flag' => '🇰🇼'],
    'KZT' => ['name' => 'Kazakhstani Tenge', 'symbol' => 'KZT', 'flag' => '🇰🇿'],
    'LBP' => ['name' => 'Lebanese Pound', 'symbol' => 'LBP', 'flag' => '🇱🇧'],
    'LKR' => ['name' => 'Sri Lankan Rupee', 'symbol' => 'Rs', 'flag' => '🇱🇰'],
    'MAD' => ['name' => 'Moroccan Dirham', 'symbol' => 'MAD', 'flag' => '🇲🇦'],
    'MUR' => ['name' => 'Mauritian Rupee', 'symbol' => 'MUR', 'flag' => '🇲🇺'],
    'MXN' => ['name' => 'Mexican Peso', 'symbol' => 'MX$', 'flag' => '🇲🇽'],
    'MYR' => ['name' => 'Malaysian Ringgit', 'symbol' => 'RM', 'flag' => '🇲🇾'],
    'NGN' => ['name' => 'Nigerian Naira', 'symbol' => '₦', 'flag' => '🇳🇬'],
    'NOK' => ['name' => 'Norwegian Krone', 'symbol' => 'kr', 'flag' => '🇳🇴'],
    'NPR' => ['name' => 'Nepalese Rupee', 'symbol' => 'Rs', 'flag' => '🇳🇵'],
    'NZD' => ['name' => 'New Zealand Dollar', 'symbol' => 'NZ$', 'flag' => '🇳🇿'],
    'OMR' => ['name' => 'Omani Rial', 'symbol' => 'OMR', 'flag' => '🇴🇲'],
    'PEN' => ['name' => 'Peruvian Sol', 'symbol' => 'S/', 'flag' => '🇵🇪'],
    'PHP' => ['name' => 'Philippine Peso', 'symbol' => '₱', 'flag' => '🇵🇭'],
    'PKR' => ['name' => 'Pakistani Rupee', 'symbol' => 'Rs', 'flag' => '🇵🇰'],
    'PLN' => ['name' => 'Polish Zloty', 'symbol' => 'zl', 'flag' => '🇵🇱'],
    'QAR' => ['name' => 'Qatari Riyal', 'symbol' => 'QAR', 'flag' => '🇶🇦'],
    'RON' => ['name' => 'Romanian Leu', 'symbol' => 'RON', 'flag' => '🇷🇴'],
    'RSD' => ['name' => 'Serbian Dinar', 'symbol' => 'RSD', 'flag' => '🇷🇸'],
    'RUB' => ['name' => 'Russian Ruble', 'symbol' => '₽', 'flag' => '🇷🇺'],
    'SAR' => ['name' => 'Saudi Riyal', 'symbol' => 'SAR', 'flag' => '🇸🇦'],
    'SEK' => ['name' => 'Swedish Krona', 'symbol' => 'kr', 'flag' => '🇸🇪'],
    'SGD' => ['name' => 'Singapore Dollar', 'symbol' => 'S$', 'flag' => '🇸🇬'],
    'THB' => ['name' => 'Thai Baht', 'symbol' => '฿', 'flag' => '🇹🇭'],
    'TND' => ['name' => 'Tunisian Dinar', 'symbol' => 'TND', 'flag' => '🇹🇳'],
    'TRY' => ['name' => 'Turkish Lira', 'symbol' => '₺', 'flag' => '🇹🇷'],
    'TWD' => ['name' => 'Taiwan Dollar', 'symbol' => 'NT$', 'flag' => '🇹🇼'],
    'TZS' => ['name' => 'Tanzanian Shilling', 'symbol' => 'TZS', 'flag' => '🇹🇿'],
    'UAH' => ['name' => 'Ukrainian Hryvnia', 'symbol' => '₴', 'flag' => '🇺🇦'],
    'UGX' => ['name' => 'Ugandan Shilling', 'symbol' => 'UGX', 'flag' => '🇺🇬'],
    'USD' => ['name' => 'US Dollar', 'symbol' => '$', 'flag' => '🇺🇸'],
    'UYU' => ['name' => 'Uruguayan Peso', 'symbol' => 'UYU', 'flag' => '🇺🇾'],
    'VND' => ['name' => 'Vietnamese Dong', 'symbol' => '₫', 'flag' => '🇻🇳'],
    'XAF' => ['name' => 'Central African CFA Franc', 'symbol' => 'FCFA', 'flag' => '🇨🇲'],
    'XOF' => ['name' => 'West African CFA Franc', 'symbol' => 'CFA', 'flag' => '🇸🇳'],
    'ZAR' => ['name' => 'South African Rand', 'symbol' => 'R', 'flag' => '🇿🇦'],
];
